---
name: License Check
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    - sync-main-1218
permissions:
  contents: read
jobs:
  license-checker:
    uses: secretflow/.github/.github/workflows/license-check.yml@main
